spring:
  application:
    name: mcp-client
  profiles:
    active: dev
  ai:
    embedding:
      transformer:
        onnx:
          modelUri: classpath:/onnx/all-MiniLM-L6-v2/model.onnx
          modelOutputName: last_hidden_state
        tokenizer:
          uri: classpath:/onnx/all-MiniLM-L6-v2/tokenizer.json

    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      chat:
        options:
          model: ${OPENAI_MODEL}
    vectorstore:
      redis:
        initialize-schema: true         # 是否初始化所需的模式
        index-name: lee-vectorstore     # 用于存储向量的索引名称
        prefix: 'embedding:'             # Redis 键的前缀
  data:
    redis:
      host: 127.0.0.1
      port: 9379
      password: 123456
#    embedding:
#      transformer:
#        cache:
#          directory: classpath:onnx/all-MiniLM-L6-v2/model.onnx
#          enabled: true

#    mcp:
#      client:
#        enabled: true
#        name: spring-ai-mcp-client
